version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: event-reward-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-reward-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: event-reward-gateway
    restart: always
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${GATEWAY_PORT}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - EVENT_SERVICE_URL=${EVENT_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - auth
      - event
    networks:
      - event-reward-network

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: event-reward-auth
    restart: always
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${AUTH_PORT}
      - MONGODB_URI=mongodb://root:${MONGO_PASSWORD}@mongodb:27017/auth?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - mongodb
    networks:
      - event-reward-network

  event:
    build:
      context: ./event
      dockerfile: Dockerfile
    container_name: event-reward-event
    restart: always
    ports:
      - "${EVENT_PORT}:${EVENT_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${EVENT_PORT}
      - MONGODB_URI=mongodb://root:${MONGO_PASSWORD}@mongodb:27017/event?authSource=admin
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - mongodb
    networks:
      - event-reward-network

networks:
  event-reward-network:
    driver: bridge

volumes:
  mongodb_data:
